# alias personal
alias Discord="com.discordapp.Discord" "$HOME/.zshrc"
alias Spotify="com.spotify.Client" "$HOME/.zshrc"
alias Teams="com.github.IsmaelMartinez.teams_for_linux" "$HOME/.zshrc"
alias ls="eza --icons --color=always --group-directories-first" "$HOME/.zshrc"
alias tree="eza --icons --color=always --group-directories-first --tree" "$HOME/.zshrc"
alias grep="grep --color=auto"
alias shutdown="shutdown -now"
alias Vscode="code ."
alias gl="git pull"
alias gc="git commit -m"
alias gp="git push"
alias gsw="git switch"
alias gstatus="git status"
alias gpbranch="git push --set-upstream origin"
alias tlp="sudo systemctl start tlp.service"
alias hasura-console="hasura console --no-browser"
